// Kapsamli NACE Rev.2 faaliyet kodlari - Mali musavirler icin
const NACE_CODES = [
  // TARIM, ORMANCILIK VE BALIKCILIK (01-03)
  { code: '0111', desc: 'Tahil (pirinc haric), baklagil ve yagli tohum yetistiriciligi' },
  { code: '0113', desc: 'Sebze, kavun, karpuz, kok ve yumru bitki yetistiriciligi' },
  { code: '0116', desc: 'Lif bitkileri yetistiriciligi' },
  { code: '0119', desc: 'Diger tek yillik bitkilerin yetistiriciligi' },
  { code: '0121', desc: 'Uzum yetistiriciligi' },
  { code: '0124', desc: 'Yumusak cekirdekli meyve yetistiriciligi' },
  { code: '0125', desc: 'Diger agac ve calimsi meyve yetistiriciligi' },
  { code: '0126', desc: 'Yagli meyve yetistiriciligi' },
  { code: '0127', desc: 'Icecek bitkisi yetistiriciligi' },
  { code: '0130', desc: 'Bitki cogaltimi' },
  { code: '0141', desc: 'Sut sigirciligi' },
  { code: '0142', desc: 'Diger sigir ve mandalarin yetistiriciligi' },
  { code: '0145', desc: 'Koyun ve keci yetistiriciligi' },
  { code: '0146', desc: 'Domuz yetistiriciligi' },
  { code: '0147', desc: 'Kumes hayvanlari yetistiriciligi' },
  { code: '0149', desc: 'Diger hayvanlarin yetistiriciligi' },
  { code: '0150', desc: 'Karma ciftcilik' },
  { code: '0161', desc: 'Bitkisel uretimi destekleyici faaliyetler' },
  { code: '0162', desc: 'Hayvansal uretimi destekleyici faaliyetler' },
  { code: '0210', desc: 'Ormancilik ve diger ormancilik faaliyetleri' },
  { code: '0220', desc: 'Tomrukculuk' },
  { code: '0311', desc: 'Deniz balikciligii' },
  { code: '0312', desc: 'Tatli su balikciligii' },
  { code: '0321', desc: 'Deniz su urunleri yetistiriciligi' },
  { code: '0322', desc: 'Tatli su urunleri yetistiriciligi' },

  // MADENCILIK VE TAS OCAKCILIGII (05-09)
  { code: '0510', desc: 'Tas komuru madenciligi' },
  { code: '0520', desc: 'Linyit madenciligi' },
  { code: '0610', desc: 'Ham petrol cikarimi' },
  { code: '0620', desc: 'Dogal gaz cikarimi' },
  { code: '0710', desc: 'Demir cevheri madenciligi' },
  { code: '0729', desc: 'Diger demir disi metal cevheri madenciligi' },
  { code: '0811', desc: 'Sus ve yapi tasi, kirectas, alcitas, tebesiir madenciligi' },
  { code: '0812', desc: 'Cakil ve kum ocaklari, kil ve kaolin cikarimi' },
  { code: '0891', desc: 'Kimyasal ve gubrelik mineral madenciligi' },
  { code: '0899', desc: 'Baska yerde siniflandirilmamis diger madencilik ve tasocakciligii' },
  { code: '0910', desc: 'Petrol ve dogal gaz cikarimini destekleyici hizmet faaliyetleri' },

  // IMALAT (10-33)
  { code: '1011', desc: 'Etin islenmesi ve saklanmasi' },
  { code: '1012', desc: 'Kumes hayvanlari etinin islenmesi ve saklanmasi' },
  { code: '1013', desc: 'Et ve kumes hayvanlari etinden uretilen urunlerin imalati' },
  { code: '1020', desc: 'Balik, kabuklu ve yumusakca deniz hayvanlari isleme ve saklama' },
  { code: '1031', desc: 'Patatesin islenmesi ve saklanmasi' },
  { code: '1039', desc: 'Diger meyve ve sebzelerin islenmesi ve saklanmasi' },
  { code: '1041', desc: 'Sivi ve kati yag imalati' },
  { code: '1042', desc: 'Margarin ve benzeri yenilebilir yaglarin imalati' },
  { code: '1051', desc: 'Sut isleme ve peynir imalati' },
  { code: '1052', desc: 'Dondurma imalati' },
  { code: '1061', desc: 'Ogutulmus tahil urunleri imalati' },
  { code: '1062', desc: 'Nisasta ve nisastali urunlerin imalati' },
  { code: '1071', desc: 'Ekmek, taze pastane urunleri ve taze kek imalati' },
  { code: '1072', desc: 'Peksimeti, biskuvi; dayanikli pastane ve kek imalati' },
  { code: '1073', desc: 'Makarna, eriste, kuskus vb. hamur isleri imalati' },
  { code: '1081', desc: 'Seker imalati' },
  { code: '1082', desc: 'Kakao, cikolata ve seker sekerlemesi imalati' },
  { code: '1083', desc: 'Cay ve kahve islenmesi' },
  { code: '1084', desc: 'Baharat, sos, sirke ve diger cesni maddelerinin imalati' },
  { code: '1085', desc: 'Hazir yemeklerin imalati' },
  { code: '1086', desc: 'Homojenize gida ve diyetetik gida urunleri imalati' },
  { code: '1089', desc: 'Baska yerde siniflandirilmamis diger gida maddelerinin imalati' },
  { code: '1101', desc: 'Alkollucici icki damitilmasi, aritilmasi ve harmanlari' },
  { code: '1102', desc: 'Uzum sarabi imalati' },
  { code: '1103', desc: 'Bira imalati' },
  { code: '1104', desc: 'Malt imalati' },
  { code: '1105', desc: 'Meyveli, gazli vb. alkolsuz icecek imalati; maden suyu imalati' },
  { code: '1200', desc: 'Tutun urunleri imalati' },
  { code: '1310', desc: 'Tekstil elyafinin hazirlanmasi ve bukulm.' },
  { code: '1320', desc: 'Dokuma' },
  { code: '1330', desc: 'Tekstil urunlerinin terbiyesi' },
  { code: '1391', desc: 'Orme (triko) ve tirkoraj kumaslarin imalati' },
  { code: '1392', desc: 'Konfeksiyon disindaki hazir tekstil urunleri imalati' },
  { code: '1393', desc: 'Hali ve kilim imalati' },
  { code: '1394', desc: 'Sicim, ip, halat ve ag imalati' },
  { code: '1395', desc: 'Dokusuz kumaslar ve dokusuz kumas urunleri imalati' },
  { code: '1396', desc: 'Diger teknik ve endustriyel tekstillerin imalati' },
  { code: '1399', desc: 'Baska yerde siniflandirilmamis diger tekstil urunleri imalati' },
  { code: '1411', desc: 'Deri giyim esyasi imalati' },
  { code: '1412', desc: 'Is giysileri imalati' },
  { code: '1413', desc: 'Diger dis giyim esyasi imalati' },
  { code: '1414', desc: 'Ic giyim esyasi imalati' },
  { code: '1419', desc: 'Diger giyim esyasi ve aksesuarlari imalati' },
  { code: '1420', desc: 'Kurk esya imalati' },
  { code: '1431', desc: 'Corap imalati' },
  { code: '1439', desc: 'Diger orme (triko) giyim esyasi imalati' },
  { code: '1511', desc: 'Deri ve post tabaklanmasi, islenm.; bavul, canta imalati' },
  { code: '1512', desc: 'Bavul, el cantasi, saraciye vb. kosumculuk urunleri imalati' },
  { code: '1520', desc: 'Ayakkabi imalati' },
  { code: '1610', desc: 'Kerestenin bicilmesi ve rendelenmesi' },
  { code: '1621', desc: 'Kontrplak, sunta, levha ve panel imalati' },
  { code: '1622', desc: 'Birlestirilmis parke paneli imalati' },
  { code: '1623', desc: 'Diger yapi dogramaciligii ve marangozluk urunleri imalati' },
  { code: '1624', desc: 'Ahsap konteyner imalati' },
  { code: '1629', desc: 'Diger agac urunleri imalati; hasir ve orgu imalati' },
  { code: '1711', desc: 'Kagit hamuru imalati' },
  { code: '1712', desc: 'Kagit ve mukavva imalati' },
  { code: '1721', desc: 'Oluklu kagit ve mukavva imalati; kagit ve mukavva ambalaj' },
  { code: '1722', desc: 'Kagit ev esyasi, hijyen ve tuvalet malzemeleri imalati' },
  { code: '1723', desc: 'Kagit kirtasiye urunleri imalati' },
  { code: '1729', desc: 'Diger kagit ve mukavva urunleri imalati' },
  { code: '1811', desc: 'Gazete basilik faaliyetleri' },
  { code: '1812', desc: 'Diger matbaacilik (baski) faaliyetleri' },
  { code: '1813', desc: 'Baski oncesi (pre-press) ve baski ortami hazirlik faaliyetleri' },
  { code: '1814', desc: 'Ciltcilik ve ilgili faaliyetler' },
  { code: '1820', desc: 'Kayitli medyanin cogaltilmasi' },
  { code: '1910', desc: 'Kok firini urunleri imalati' },
  { code: '1920', desc: 'Rafine petrol urunleri imalati' },
  { code: '2011', desc: 'Sanayi gazlari imalati' },
  { code: '2012', desc: 'Boya maddeleri ve pigment imalati' },
  { code: '2013', desc: 'Diger anorganik temel kimyasal madde imalati' },
  { code: '2014', desc: 'Diger organik temel kimyasal madde imalati' },
  { code: '2015', desc: 'Kimyasal gubre ve azotlu bilesik imalati' },
  { code: '2016', desc: 'Birincil formda plastik hammadde imalati' },
  { code: '2017', desc: 'Birincil formda sentetik kaucuk imalati' },
  { code: '2020', desc: 'Hasat ilaci ve diger zirai kimyasal urun imalati' },
  { code: '2030', desc: 'Boya, vernik ve benzeri kaplamalar, murekkepler imalati' },
  { code: '2041', desc: 'Sabun, deterjan, temizlik ve cilalama urunleri imalati' },
  { code: '2042', desc: 'Parfum, kozmetik urunleri, tuvalet malz. imalati' },
  { code: '2051', desc: 'Patlayici madde imalati' },
  { code: '2052', desc: 'Tutkal imalati' },
  { code: '2053', desc: 'Ucucu yag imalati' },
  { code: '2059', desc: 'Baska yerde siniflandirilmamis diger kimyasal urunlerin imalati' },
  { code: '2060', desc: 'Suni veya sentetik elyaf imalati' },
  { code: '2110', desc: 'Temel eczacilik urunlerinin imalati' },
  { code: '2120', desc: 'Eczaciliga ait ilac imalati' },
  { code: '2211', desc: 'Ic ve dis lastik imalati; lastik kaplamaciligii' },
  { code: '2219', desc: 'Diger kaucuk urunlerin imalati' },
  { code: '2221', desc: 'Plastik tabaka, levha, tup ve profil imalati' },
  { code: '2222', desc: 'Plastik torba, canta, cuval, posa, kutu, kasa vb. ambalaj malz.' },
  { code: '2223', desc: 'Plastik insaat malzemeleri imalati' },
  { code: '2229', desc: 'Diger plastik urunlerin imalati' },
  { code: '2311', desc: 'Duz cam imalati' },
  { code: '2312', desc: 'Duz camin sekillendirilmesi ve islenmesi' },
  { code: '2313', desc: 'Cukur cam imalati' },
  { code: '2314', desc: 'Cam elyafi imalati' },
  { code: '2319', desc: 'Diger cam urunlerinin imalati ve islenmesi' },
  { code: '2320', desc: 'Atesye dayanikli urunlerin imalati' },
  { code: '2331', desc: 'Seramik karo ve kaldiirim tasi imalati' },
  { code: '2332', desc: 'Pisirmis kilden tugla, karo ve insaat malzemeleri imalati' },
  { code: '2341', desc: 'Seramik ev ve sus esyasi imalati' },
  { code: '2342', desc: 'Seramik sihhi urunlerin imalati' },
  { code: '2351', desc: 'Cimento imalati' },
  { code: '2352', desc: 'Kirecve alci imalati' },
  { code: '2361', desc: 'Insaat amacli beton urunleri imalati' },
  { code: '2362', desc: 'Insaat amacli alci urunleri imalati' },
  { code: '2363', desc: 'Hazir beton imalati' },
  { code: '2364', desc: 'Toz harc imalati' },
  { code: '2365', desc: 'Lif ve cimento karisimi urunlerin imalati' },
  { code: '2369', desc: 'Diger beton, alci ve cimento urunleri imalati' },
  { code: '2370', desc: 'Tasi kesme, sekil verme ve isleme' },
  { code: '2391', desc: 'Asindirici urunlerin imalati' },
  { code: '2399', desc: 'Baska yerde siniflandirilmamis metalik olmayan mineral urunlerin imalati' },
  { code: '2410', desc: 'Ana demir ve celik urunleri ile ferro alyasimlar imalati' },
  { code: '2420', desc: 'Celik boru, profil vb. imalati' },
  { code: '2431', desc: 'Celik bar soguk cekme' },
  { code: '2432', desc: 'Dar serit soguk haddeleme' },
  { code: '2433', desc: 'Soguk sekillendirme veya katlama' },
  { code: '2434', desc: 'Celik tel cekme' },
  { code: '2441', desc: 'Degerli metal uretimi' },
  { code: '2442', desc: 'Aluminyum uretimi' },
  { code: '2443', desc: 'Kursun, cinko ve kalay uretimi' },
  { code: '2444', desc: 'Bakir uretimi' },
  { code: '2445', desc: 'Diger demir disi metal uretimi' },
  { code: '2451', desc: 'Demir dokum' },
  { code: '2452', desc: 'Celik dokum' },
  { code: '2453', desc: 'Hafif metal dokum' },
  { code: '2454', desc: 'Diger demir disi metal dokum' },
  { code: '2511', desc: 'Metal yapi ve yapilarinin parcalarinin imalati' },
  { code: '2512', desc: 'Metal kapi ve pencere imalati' },
  { code: '2521', desc: 'Merkezi isitma radyatorleri ve sicak su kazanlari imalati' },
  { code: '2529', desc: 'Metalden diger tank, sarnic ve konteyner imalati' },
  { code: '2530', desc: 'Buhar kazani imalati (merkezi isitma sicak su kazanlari haric)' },
  { code: '2540', desc: 'Silah ve muhimmat imalati' },
  { code: '2550', desc: 'Metalin dovulmesi, preslenmesi, baskilanmasi ve haddelenmesi' },
  { code: '2561', desc: 'Metallerin islenmesi ve kaplanmasi' },
  { code: '2562', desc: 'Metallerin makinede islenmesi' },
  { code: '2571', desc: 'Bicak, tasaksuz ve kesici aletlerin imalati' },
  { code: '2572', desc: 'Kilit ve mentese imalati' },
  { code: '2573', desc: 'El aletleri imalati' },
  { code: '2591', desc: 'Celik varil ve benzeri konteynerlerin imalati' },
  { code: '2592', desc: 'Hafif metallerden ambalaj malzemesi imalati' },
  { code: '2593', desc: 'Tel urunleri, zincir ve yay imalati' },
  { code: '2594', desc: 'Baglanti malzemesi ve vida urunleri imalati' },
  { code: '2599', desc: 'Baska yerde siniflandirilmamis diger fabrikasyon metal urun imalati' },
  { code: '2611', desc: 'Elektronik bilesenlerin imalati' },
  { code: '2612', desc: 'Yuklu elektronik kart imalati' },
  { code: '2620', desc: 'Bilgisayar ve cevre birimlerin imalati' },
  { code: '2630', desc: 'Iletisim ekipmanlarinin imalati' },
  { code: '2640', desc: 'Tuketici elektronigi imalati' },
  { code: '2651', desc: 'Olcme, test ve navigasyon ekipmanlari imalati' },
  { code: '2652', desc: 'Saat imalati' },
  { code: '2660', desc: 'Isinlama, elektromedikal ve elektroterapotik cihaz imalati' },
  { code: '2670', desc: 'Optik aletler ve fotograf ekipmanlari imalati' },
  { code: '2680', desc: 'Manyetik ve optik kayit ortami imalati' },
  { code: '2711', desc: 'Elektrik motorlari, jenerator ve transformator imalati' },
  { code: '2712', desc: 'Elektrik dagitim ve kontrol cihazlari imalati' },
  { code: '2720', desc: 'Akumulator ve pil imalati' },
  { code: '2731', desc: 'Fiber optik kablo imalati' },
  { code: '2732', desc: 'Diger elektronik ve elektrik teli ve kablosu imalati' },
  { code: '2733', desc: 'Kablo baglanti urunleri imalati' },
  { code: '2740', desc: 'Elektrikli aydinlatma ekipmanlari imalati' },
  { code: '2751', desc: 'Elektrikli ev aletleri imalati' },
  { code: '2752', desc: 'Elektriksiz ev aletleri imalati' },
  { code: '2790', desc: 'Diger elektrikli ekipman imalati' },
  { code: '2811', desc: 'Motor ve turbin imalati (ucak, tasit ve bisiklet motorlari haric)' },
  { code: '2812', desc: 'Akiskan guc ekipmanlari imalati' },
  { code: '2813', desc: 'Diger pompa ve kompresur imalati' },
  { code: '2814', desc: 'Diger musluk ve valf imalati' },
  { code: '2815', desc: 'Yatak, disli, disli takimi ve kumanda elemanlari imalati' },
  { code: '2821', desc: 'Firin, ocak ve brulor imalati' },
  { code: '2822', desc: 'Kaldirma ve tasima ekipmani imalati' },
  { code: '2823', desc: 'Buro makine ve ekipmanlari imalati (bilgisayar haric)' },
  { code: '2824', desc: 'Motorlu veya pnomatik el aletleri imalati' },
  { code: '2825', desc: 'Sanayi tipi sogutma ve havalandirma ekipmanlari imalati' },
  { code: '2829', desc: 'Baska yerde siniflandirilmamis diger genel amacli makine imalati' },
  { code: '2830', desc: 'Tarim ve ormancilik makinelerinin imalati' },
  { code: '2841', desc: 'Metal isleme makineleri imalati' },
  { code: '2849', desc: 'Diger takim tezgahlari imalati' },
  { code: '2891', desc: 'Metalurji makineleri imalati' },
  { code: '2892', desc: 'Madencilik, tasocakciligii ve insaat makineleri imalati' },
  { code: '2893', desc: 'Gida, icecek ve tutun isleme makineleri imalati' },
  { code: '2894', desc: 'Tekstil, giyim esyasi ve deri isleme makineleri imalati' },
  { code: '2895', desc: 'Kagit ve mukavva imalati icin makinelerin imalati' },
  { code: '2896', desc: 'Plastik ve kaucuk makineleri imalati' },
  { code: '2899', desc: 'Baska yerde siniflandirilmamis ozel amacli diger makine imalati' },
  { code: '2910', desc: 'Motorlu kara tasiti imalati' },
  { code: '2920', desc: 'Motorlu kara tasitlari icin kaporta imalati; romorlarin imalati' },
  { code: '2931', desc: 'Motorlu kara tasitlari icin elektrikli ve elektronik aksam imalati' },
  { code: '2932', desc: 'Motorlu kara tasitlari icin diger aksam ve parca imalati' },
  { code: '3011', desc: 'Gemi ve yat yapimi' },
  { code: '3012', desc: 'Eglence ve spor amacli tekne yapimi' },
  { code: '3020', desc: 'Demir yolu ve tramvay lokomotif ve vagon imalati' },
  { code: '3030', desc: 'Hava ve uzay araclari ile ilgili makinelerin imalati' },
  { code: '3040', desc: 'Askeri savas araclari imalati' },
  { code: '3091', desc: 'Motosiklet imalati' },
  { code: '3092', desc: 'Bisiklet ve engelli arabalari imalati' },
  { code: '3099', desc: 'Baska yerde siniflandirilmamis diger ulasim araclari imalati' },
  { code: '3100', desc: 'Mobilya imalati' },
  { code: '3211', desc: 'Madensel para basimi' },
  { code: '3212', desc: 'Kuyumculuk ve benzeri esyalarin imalati' },
  { code: '3213', desc: 'Imitasyon (taklit) takilarin ve ilgili urunlerin imalati' },
  { code: '3220', desc: 'Muzik aletleri imalati' },
  { code: '3230', desc: 'Spor malzemeleri imalati' },
  { code: '3240', desc: 'Oyun ve oyuncak imalati' },
  { code: '3250', desc: 'Tibbi ve disi hekim aletleri ve malzemeleri imalati' },
  { code: '3291', desc: 'Supurge ve firca imalati' },
  { code: '3299', desc: 'Baska yerde siniflandirilmamis diger imalatlar' },
  { code: '3311', desc: 'Fabrikasyon metal urunlerinin onarimi' },
  { code: '3312', desc: 'Makine ve ekipmanlarin onarimi' },
  { code: '3313', desc: 'Elektronik ve optik ekipmanlarin onarimi' },
  { code: '3314', desc: 'Elektrikli ekipmanlarin onarimi' },
  { code: '3315', desc: 'Gemilerin ve teknelerin onarimi ve bakimi' },
  { code: '3316', desc: 'Hava ve uzay araclarinin onarimi ve bakimi' },
  { code: '3317', desc: 'Diger ulasim araclari ve ekipmanlarinin onarimi ve bakimi' },
  { code: '3319', desc: 'Diger ekipmanlarin onarimi' },
  { code: '3320', desc: 'Sanayi makinelerinin ve ekipmanlarinin kurulumu' },

  // ELEKTRIK, GAZ, BUHAR (35)
  { code: '3511', desc: 'Elektrik uretimi' },
  { code: '3512', desc: 'Elektrik iletimi' },
  { code: '3513', desc: 'Elektrik dagitimi' },
  { code: '3514', desc: 'Elektrik ticareti' },
  { code: '3521', desc: 'Gaz yakitlarin imalati' },
  { code: '3522', desc: 'Boru hatti ile gaz yakitlarin dagitimi' },
  { code: '3523', desc: 'Boru hatti disinda gaz yakitlarin ticareti' },
  { code: '3530', desc: 'Buhar ve iklimlendirme temini' },

  // SU TEMINI, ATIK SU YON. (36-39)
  { code: '3600', desc: 'Suyun toplanmasi, aritilmasi ve dagitimi' },
  { code: '3700', desc: 'Kanalizasyon' },
  { code: '3811', desc: 'Tehlikesiz atiklarin toplanmasi' },
  { code: '3812', desc: 'Tehlikeli atiklarin toplanmasi' },
  { code: '3821', desc: 'Tehlikesiz atiklarin islenmesi ve bertarafi' },
  { code: '3822', desc: 'Tehlikeli atiklarin islenmesi ve bertarafi' },
  { code: '3831', desc: 'Hurdalarin parcalanmasi (sokulumu)' },
  { code: '3832', desc: 'Tasniflenmis malzemelerin geri kazanimi' },
  { code: '3900', desc: 'Iyilestirme faaliyetleri ve diger atik yonetimi hizmetleri' },

  // INSAAT (41-43)
  { code: '4110', desc: 'Ikamet amacli binalarin insaati (gelistirme dahil)' },
  { code: '4120', desc: 'Ikamet amacli olmayan binalarin insaati' },
  { code: '4211', desc: 'Kara yollari ve demir yollari insaati' },
  { code: '4212', desc: 'Yer alti ve yer ustu demiryollari insaati' },
  { code: '4213', desc: 'Kopru ve tunel insaati' },
  { code: '4221', desc: 'Akiskanlar icin hizmet projeleri insaati' },
  { code: '4222', desc: 'Elektrik ve telekomun. icin hizmet projeleri insaati' },
  { code: '4291', desc: 'Su projeleri insaati' },
  { code: '4299', desc: 'Baska yerde siniflandirilmamis diger insaat projeleri' },
  { code: '4311', desc: 'Yikma isleri' },
  { code: '4312', desc: 'Insaat alani hazirlik isleri' },
  { code: '4313', desc: 'Test delgi ve sondaj' },
  { code: '4321', desc: 'Elektrik tesisati' },
  { code: '4322', desc: 'Sihhi tesisat, isitma ve klima tesisati' },
  { code: '4329', desc: 'Diger insaat tesisati' },
  { code: '4331', desc: 'Siva isleri' },
  { code: '4332', desc: 'Dograma ve marangozluk isleri' },
  { code: '4333', desc: 'Yer ve duvar kaplama' },
  { code: '4334', desc: 'Boya ve cam isleri' },
  { code: '4339', desc: 'Diger bina tamamlama ve bitirme isleri' },
  { code: '4391', desc: 'Cati isleri' },
  { code: '4399', desc: 'Baska yerde siniflandirilmamis diger ozel insaat faaliyetleri' },

  // TOPTAN VE PERAKENDE TIC. (45-47)
  { code: '4511', desc: 'Otomobil ve hafif motorlu tasit ticareti' },
  { code: '4519', desc: 'Diger motorlu tasit ticareti' },
  { code: '4520', desc: 'Motorlu tasit bakim ve onarimi' },
  { code: '4531', desc: 'Motorlu tasit parcalari ve aksesuarlari toptan ticareti' },
  { code: '4532', desc: 'Motorlu tasit parcalari ve aksesuarlari perakende ticareti' },
  { code: '4540', desc: 'Motosiklet ve ilgili parca ve aksesuarlarin ticareti, bakimi ve onarimi' },
  { code: '4611', desc: 'Tarim urunleri, canli hayvan, tekstil hammaddeleri ticaretinde aracilik' },
  { code: '4612', desc: 'Yakit, maden, metal ve end. kim. mad. toptan tic. aracilari' },
  { code: '4613', desc: 'Kereste, insaat malzemeleri ve sihhi tesisatin ticaretinde aracilik' },
  { code: '4614', desc: 'Makine, end. donanim, gemi ve ucak ticaret aracilari' },
  { code: '4615', desc: 'Mobilya, ev esyasi ve nalbur ticaretinde aracilik' },
  { code: '4616', desc: 'Tekstil, giyim esyasi, ayakkabi ve deri ticaretinde aracilik' },
  { code: '4617', desc: 'Gida, icecek ve tutun ticaretinde aracilik' },
  { code: '4618', desc: 'Diger belirli urunlerin toptan ticaretinde uzman aracilar' },
  { code: '4619', desc: 'Cesitli mallar uzerinde aracilik' },
  { code: '4621', desc: 'Tahil, tutun, tohum ve hayvan yemi toptan ticareti' },
  { code: '4622', desc: 'Cicek ve bitki toptan ticareti' },
  { code: '4623', desc: 'Canli hayvan toptan ticareti' },
  { code: '4624', desc: 'Ham deri, post ve islenm. deri toptan ticareti' },
  { code: '4631', desc: 'Meyve ve sebze toptan ticareti' },
  { code: '4632', desc: 'Et ve et urunleri toptan ticareti' },
  { code: '4633', desc: 'Sut urunleri, yumurta, sivi ve kati yag toptan ticareti' },
  { code: '4634', desc: 'Icecek toptan ticareti' },
  { code: '4635', desc: 'Tutun urunleri toptan ticareti' },
  { code: '4636', desc: 'Seker, cikolata ve sekerlemeler toptan ticareti' },
  { code: '4637', desc: 'Kahve, cay, kakao ve baharat toptan ticareti' },
  { code: '4638', desc: 'Balik, kabuklu ve yumusakca deniz hayvanlari toptan ticareti' },
  { code: '4639', desc: 'Gida, icecek ve tutun urunleri toptan ticareti' },
  { code: '4641', desc: 'Tekstil urunleri toptan ticareti' },
  { code: '4642', desc: 'Giyim esyasi ve ayakkabi toptan ticareti' },
  { code: '4643', desc: 'Elektrikli ev aletleri toptan ticareti' },
  { code: '4644', desc: 'Porselen, cam esya ve temizlik maddeleri toptan ticareti' },
  { code: '4645', desc: 'Parfumeri ve kozmetik urunleri toptan ticareti' },
  { code: '4646', desc: 'Eczacilik urunleri toptan ticareti' },
  { code: '4647', desc: 'Mobilya, hali ve aydinlatma ekipmanlari toptan ticareti' },
  { code: '4648', desc: 'Saat ve kuyumculuk urunleri toptan ticareti' },
  { code: '4649', desc: 'Diger ev esyalari toptan ticareti' },
  { code: '4651', desc: 'Bilgisayar, cevre birimleri ve yazilim toptan ticareti' },
  { code: '4652', desc: 'Elektronik ve telekomun. parcalari ve ekipmanlari toptan ticareti' },
  { code: '4661', desc: 'Tarim makine ve ekipmanlari ile aksesuarlarinin toptan ticareti' },
  { code: '4662', desc: 'Takim tezgahlari toptan ticareti' },
  { code: '4663', desc: 'Maden, insaat ve ins. muhendisligi makineleri toptan ticareti' },
  { code: '4664', desc: 'Tekstil sanayi makineleri, dikiis ve orgu makineleri toptan tic.' },
  { code: '4665', desc: 'Buro mobilyalari toptan ticareti' },
  { code: '4666', desc: 'Diger buro makine ve ekipmanlari toptan ticareti' },
  { code: '4669', desc: 'Diger makine ve ekipman toptan ticareti' },
  { code: '4671', desc: 'Kati, sivi ve gazli yakit ve benzeri urunlerin toptan ticareti' },
  { code: '4672', desc: 'Metal ve metal cevheri toptan ticareti' },
  { code: '4673', desc: 'Agac, insaat malzemesi ve sihhi tesisat ekipmani toptan ticareti' },
  { code: '4674', desc: 'Hirdavat, sihhi tesisat ve isitma tesisati malzemeleri toptan tic.' },
  { code: '4675', desc: 'Kimyasal urunlerin toptan ticareti' },
  { code: '4676', desc: 'Diger ara urunlerin toptan ticareti' },
  { code: '4677', desc: 'Hurda ve atik toptan ticareti' },
  { code: '4690', desc: 'Belirli bir mala tahsis olmayan toptan ticaret' },
  { code: '4711', desc: 'Gida agirlikli marketler (supermarket, bakkal vb.)' },
  { code: '4719', desc: 'Belirli bir mala tahsis olmayan magazalarda perakende ticaret' },
  { code: '4721', desc: 'Meyve ve sebze perakende ticareti' },
  { code: '4722', desc: 'Et ve et urunleri perakende ticareti' },
  { code: '4723', desc: 'Balik, kabuklu ve yumusakca deniz hayvanlari perakende ticareti' },
  { code: '4724', desc: 'Ekmek, pasta, un mamulleri ve sekerli urunlerin perakende tic.' },
  { code: '4725', desc: 'Icecek perakende ticareti' },
  { code: '4726', desc: 'Tutun urunleri perakende ticareti' },
  { code: '4729', desc: 'Diger gida maddelerinin perakende ticareti' },
  { code: '4730', desc: 'Motorlu tasitlar icin yakit perakende ticareti (akaryakit)' },
  { code: '4741', desc: 'Bilgisayar, cevre birimleri ve yazilim perakende ticareti' },
  { code: '4742', desc: 'Telekomunikasyon ekipmanlari perakende ticareti' },
  { code: '4743', desc: 'Ses ve goruntu ekipmanlari perakende ticareti' },
  { code: '4751', desc: 'Tekstil urunleri perakende ticareti' },
  { code: '4752', desc: 'Hirdavat, boya ve cam perakende ticareti' },
  { code: '4753', desc: 'Hali, kilim ve duvar/yer kaplama malzemeleri perakende tic.' },
  { code: '4754', desc: 'Elektrikli ev aletleri perakende ticareti' },
  { code: '4759', desc: 'Mobilya, aydinlatma ve diger ev esyalari perakende tic.' },
  { code: '4761', desc: 'Kitap perakende ticareti' },
  { code: '4762', desc: 'Gazete ve kirtasiye urunleri perakende ticareti' },
  { code: '4763', desc: 'Muzik ve video kayitlari perakende ticareti' },
  { code: '4764', desc: 'Spor malzemeleri perakende ticareti' },
  { code: '4765', desc: 'Oyun ve oyuncak perakende ticareti' },
  { code: '4771', desc: 'Giyim esyasi perakende ticareti' },
  { code: '4772', desc: 'Ayakkabi ve deri esya perakende ticareti' },
  { code: '4773', desc: 'Eczaneler (beser ve veteriner ilac perakende ticareti)' },
  { code: '4774', desc: 'Tibbi ve ortopedik urunlerin perakende ticareti' },
  { code: '4775', desc: 'Kozmetik ve kisisel bakim urunleri perakende ticareti' },
  { code: '4776', desc: 'Cicek, bitki, tohum, gubre, evcil hayvan perakende ticareti' },
  { code: '4777', desc: 'Saat ve kuyumculuk urunleri perakende ticareti' },
  { code: '4778', desc: 'Diger yeni mallarin perakende ticareti' },
  { code: '4779', desc: 'Kullanilmis mallarin perakende ticareti' },
  { code: '4781', desc: 'Gida, icecek ve tutun urunleri seyyar saticiligii' },
  { code: '4782', desc: 'Tekstil, giyim esyasi vb. urunlerin tezgah ve pazar saticiligii' },
  { code: '4789', desc: 'Diger mallarin seyyar saticiligii' },
  { code: '4791', desc: 'Internet uzerinden perakende ticaret (e-ticaret)' },
  { code: '4799', desc: 'Magaza, tezgah ve pazar yeri disinda yapilan diger perakende tic.' },

  // ULASTIRMA VE DEPOLAMA (49-53)
  { code: '4910', desc: 'Sehirler arasi yolcu demir yolu tasimaciligi' },
  { code: '4920', desc: 'Demir yolu yuk tasimaciligi' },
  { code: '4931', desc: 'Sehir ici ve banliy kara yolcu tasimaciligi' },
  { code: '4932', desc: 'Taksi isletmeciligi' },
  { code: '4939', desc: 'Baska yerde siniflandirilmamis kara yolcu tasimaciligi' },
  { code: '4941', desc: 'Karayolu yuk tasimaciligi' },
  { code: '4942', desc: 'Evsya tasima (nakliyat)' },
  { code: '5010', desc: 'Deniz ve kiyi sularinda yolcu tasimaciligi' },
  { code: '5020', desc: 'Deniz ve kiyi sularinda yuk tasimaciligi' },
  { code: '5110', desc: 'Hava yolu ile yolcu tasimaciligi' },
  { code: '5120', desc: 'Hava yolu ile yuk tasimaciligi ve uzay tasimaciligi' },
  { code: '5210', desc: 'Depolama ve ambarlama' },
  { code: '5221', desc: 'Kara tasimaciligi icin hizmet faaliyetleri' },
  { code: '5222', desc: 'Su tasimaciligi icin hizmet faaliyetleri' },
  { code: '5223', desc: 'Hava tasimaciligi icin hizmet faaliyetleri' },
  { code: '5224', desc: 'Kargo tasima ve isleme' },
  { code: '5229', desc: 'Diger ulastirmaya yardimci faaliyetler' },
  { code: '5310', desc: 'Evrensel hizmete tabi posta faaliyetleri' },
  { code: '5320', desc: 'Diger posta ve kurye faaliyetleri' },

  // KONAKLAMA VE YIYECEK (55-56)
  { code: '5510', desc: 'Oteller ve benzeri konaklama yerleri' },
  { code: '5520', desc: 'Tatil koyleri ve diger kisa sureli konaklama yerleri' },
  { code: '5530', desc: 'Kamp alanlari, motorlu tasit park yerleri ve karavan parklari' },
  { code: '5590', desc: 'Diger konaklama yerleri' },
  { code: '5610', desc: 'Lokantalar ve seyar yemek hizmeti faaliyetleri' },
  { code: '5621', desc: 'Ozellikli yemek hazirl. ve sunumu faaliyetleri (catering)' },
  { code: '5629', desc: 'Diger yemek hizmeti faaliyetleri' },
  { code: '5630', desc: 'Icecek sunumu yapilan yerler (bar, kahve, vb.)' },

  // BILGI VE ILETISIM (58-63)
  { code: '5811', desc: 'Kitap yayimlanmasi' },
  { code: '5812', desc: 'Rehber, katalog ve postalama listeleri yayimlanmasi' },
  { code: '5813', desc: 'Gazete yayimlanmasi' },
  { code: '5814', desc: 'Dergi ve sureli yayinlarin yayimlanmasi' },
  { code: '5819', desc: 'Diger yayimcilik faaliyetleri' },
  { code: '5821', desc: 'Bilgisayar oyunlarinin yayimlanmasi' },
  { code: '5829', desc: 'Diger yazilim yayimlanmasi' },
  { code: '5911', desc: 'Sinema filmi, video ve televizyon programlari yapim faaliyetleri' },
  { code: '5912', desc: 'Sinema filmi, video ve televizyon programlari cekim sonrasi' },
  { code: '5913', desc: 'Sinema filmi, video ve televizyon programlari dagitimi' },
  { code: '5914', desc: 'Sinema filmi gosterim faaliyetleri' },
  { code: '5920', desc: 'Ses kaydi ve muzik yayimlama faaliyetleri' },
  { code: '6010', desc: 'Radyo yayinciligi' },
  { code: '6020', desc: 'Televizyon programciligi ve yayinciligi' },
  { code: '6110', desc: 'Kablolu telekomunikasyon faaliyetleri' },
  { code: '6120', desc: 'Kablosuz telekomunikasyon faaliyetleri' },
  { code: '6130', desc: 'Uydu telekomunikasyon faaliyetleri' },
  { code: '6190', desc: 'Diger telekomunikasyon faaliyetleri' },
  { code: '6201', desc: 'Bilgisayar programlama faaliyetleri (yazilim gelistirme)' },
  { code: '6202', desc: 'Bilgisayar danismanlik faaliyetleri' },
  { code: '6203', desc: 'Bilgisayar tesisleri yonetim faaliyetleri' },
  { code: '6209', desc: 'Diger bilgi teknolojisi ve bilgisayar hizmet faaliyetleri' },
  { code: '6311', desc: 'Veri isleme, barindirma (hosting) ve ilgili faaliyetler' },
  { code: '6312', desc: 'Web portali faaliyetleri' },
  { code: '6391', desc: 'Haber ajanslari faaliyetleri' },
  { code: '6399', desc: 'Baska yerde siniflandirilmamis diger bilgi hizmet faaliyetleri' },

  // FINANS VE SIGORTA (64-66)
  { code: '6411', desc: 'Merkez bankaciligi' },
  { code: '6419', desc: 'Diger parasal aracilik' },
  { code: '6420', desc: 'Holdingler' },
  { code: '6430', desc: 'Trostlar, fonlar ve benzeri mali varliklar' },
  { code: '6491', desc: 'Finansal kiralama (leasing)' },
  { code: '6492', desc: 'Diger kredi veren kuruluslar' },
  { code: '6499', desc: 'Diger finansal hizmet faaliyetleri' },
  { code: '6511', desc: 'Hayat sigortasi' },
  { code: '6512', desc: 'Hayat sigortasi haric sigortacilik' },
  { code: '6520', desc: 'Reasurans' },
  { code: '6530', desc: 'Emeklilik fonlari' },
  { code: '6611', desc: 'Finansal piyasalarin yonetimi' },
  { code: '6612', desc: 'Menkul kiymet ve emtia sozlesmeleri aracilik faaliyetleri' },
  { code: '6619', desc: 'Finansal hizmetlere yardimci diger faaliyetler' },
  { code: '6621', desc: 'Risk ve hasar degerlendirmesi' },
  { code: '6622', desc: 'Sigorta acenteleri ve brokerlerin faaliyetleri' },
  { code: '6629', desc: 'Sigorta ve emeklilige yardimci diger faaliyetler' },
  { code: '6630', desc: 'Fon yonetimi faaliyetleri' },

  // GAYRIMENKUL (68)
  { code: '6810', desc: 'Kendi gayrimenkulunu alim-satimi' },
  { code: '6820', desc: 'Kendi gayrimenkulunun kiraya verilmesi ve isletilmesi' },
  { code: '6831', desc: 'Gayrimenkul acenteleri faaliyetleri' },
  { code: '6832', desc: 'Gayrimenkul yonetimi' },

  // MESLEKI, BILIMSEL VE TEKNIK (69-75)
  { code: '6910', desc: 'Hukuk faaliyetleri (avukatlik, noterlik, hukuk danismanlik)' },
  { code: '6920', desc: 'Muhasebe, defter tutma ve denetim faaliyetleri; vergi danismanligi' },
  { code: '7010', desc: 'Merkezlerin (holding, genel mudurluk) faaliyetleri' },
  { code: '7021', desc: 'Halkla iliskiler ve iletisim faaliyetleri' },
  { code: '7022', desc: 'Isletme ve diger yonetim danismanligi faaliyetleri' },
  { code: '7111', desc: 'Mimarlik faaliyetleri' },
  { code: '7112', desc: 'Muhendislik faaliyetleri ve ilgili teknik danismanlik' },
  { code: '7120', desc: 'Teknik test ve analiz faaliyetleri' },
  { code: '7211', desc: 'Biyoteknoloji alaninda arastirma ve gelistirme' },
  { code: '7219', desc: 'Diger muhendislik ve fen bilimleri alaninda Ar-Ge' },
  { code: '7220', desc: 'Sosyal bilimler ve beser bilimler alaninda Ar-Ge' },
  { code: '7311', desc: 'Reklam ajanslari faaliyetleri' },
  { code: '7312', desc: 'Medya temsil faaliyetleri' },
  { code: '7320', desc: 'Piyasa arastirmasi ve kamuoyu yoklamasi faaliyetleri' },
  { code: '7410', desc: 'Uzmanlik gerektiren tasarim faaliyetleri (grafik, moda vb.)' },
  { code: '7420', desc: 'Fotografcilik faaliyetleri' },
  { code: '7430', desc: 'Tercume ve sozlu cevirmenlik faaliyetleri' },
  { code: '7490', desc: 'Baska yerde siniflandirilmamis diger mesleki faaliyetler' },
  { code: '7500', desc: 'Veterinerlik hizmetleri' },

  // IDARI VE DESTEK HIZMET (77-82)
  { code: '7711', desc: 'Otomobil ve hafif motorlu tasit kiralama' },
  { code: '7712', desc: 'Kamyon kiralama' },
  { code: '7721', desc: 'Eglence ve spor esyalari kiralama' },
  { code: '7722', desc: 'Video kaset ve disk kiralama' },
  { code: '7729', desc: 'Diger kisisel ve ev esyalarinin kiralanmasi ve leasingi' },
  { code: '7731', desc: 'Tarim makine ve ekipmanlari kiralama ve leasing' },
  { code: '7732', desc: 'Insaat makine ve ekipmanlari kiralama ve leasing' },
  { code: '7733', desc: 'Buro makine ve ekipmanlari kiralama ve leasing' },
  { code: '7734', desc: 'Su yolu tasimaciligi ekipmanlari kiralama ve leasing' },
  { code: '7735', desc: 'Hava tasimaciligi ekipmanlari kiralama ve leasing' },
  { code: '7739', desc: 'Baska yerde siniflandirilmamis diger makine, ekipman kiralama' },
  { code: '7740', desc: 'Fikri mulkiyet haklari ve benzeri urunlerin kiralama (lisanslama)' },
  { code: '7810', desc: 'Istihdam bulma ajanlarinin faaliyetleri' },
  { code: '7820', desc: 'Gecici is bulma ajanslarinin faaliyetleri' },
  { code: '7830', desc: 'Insan kaynaklari yonetim hizmet faaliyetleri' },
  { code: '7911', desc: 'Seyahat acentesi faaliyetleri' },
  { code: '7912', desc: 'Tur operatoru faaliyetleri' },
  { code: '7990', desc: 'Diger rezervasyon hizmetleri ve ilgili faaliyetler' },
  { code: '8010', desc: 'Ozel guvenlik faaliyetleri' },
  { code: '8020', desc: 'Guvenlik sistemleri hizmet faaliyetleri' },
  { code: '8030', desc: 'Sorusturma faaliyetleri' },
  { code: '8110', desc: 'Bina ve cevre bakim hizmetleri' },
  { code: '8121', desc: 'Binalarin genel temizligi' },
  { code: '8122', desc: 'Diger bina ve endustriyel temizlik faaliyetleri' },
  { code: '8129', desc: 'Baska yerde siniflandirilmamis diger temizlik faaliyetleri' },
  { code: '8130', desc: 'Peyzaj bakim hizmetleri' },
  { code: '8211', desc: 'Birlesik buro yonetim hizmeti faaliyetleri' },
  { code: '8219', desc: 'Fotokopi, belge hazir. ve diger ozel buro destek hizmet faaliyetleri' },
  { code: '8220', desc: 'Cagri merkezi faaliyetleri' },
  { code: '8230', desc: 'Kongre ve ticari gösteri organizasyon faaliyetleri' },
  { code: '8291', desc: 'Tahsilat ve kredi derecelendirme ajanlarinin faaliyetleri' },
  { code: '8292', desc: 'Paketleme faaliyetleri' },
  { code: '8299', desc: 'Baska yerde siniflandirilmamis diger is destek hizmet faaliyetleri' },

  // EGITIM (85)
  { code: '8510', desc: 'Okul oncesi egitim (anaokuluu)' },
  { code: '8520', desc: 'Ilkogretim' },
  { code: '8531', desc: 'Genel ortaogretim (lise)' },
  { code: '8532', desc: 'Teknik ve mesleki ortaogretim' },
  { code: '8541', desc: 'Ortaogretim sonrasi, yuksekogretim derecesi vermeyen egitim' },
  { code: '8542', desc: 'Yuksekogretim' },
  { code: '8551', desc: 'Spor ve dinlence egitimi' },
  { code: '8552', desc: 'Kultur egitimi (muzik, dans, resim, tiyatro kurslari)' },
  { code: '8553', desc: 'Suruculuk okulu faaliyetleri' },
  { code: '8559', desc: 'Baska yerde siniflandirilmamis diger egitim (dil kursu, bilgisayar kursu vb.)' },
  { code: '8560', desc: 'Egitimi destekleyici faaliyetler' },

  // INSAN SAGLIGI VE SOSYAL HIZMETLER (86-88)
  { code: '8610', desc: 'Hastane faaliyetleri' },
  { code: '8621', desc: 'Genel tip pratigi faaliyetleri (muayenehane)' },
  { code: '8622', desc: 'Uzman tip pratigi faaliyetleri' },
  { code: '8623', desc: 'Dis hekimligi faaliyetleri' },
  { code: '8690', desc: 'Diger insan sagligi hizmetleri (fizyoterapi, ambulans, laboratuvar)' },
  { code: '8710', desc: 'Barinma imkani saglanan bakimevi faaliyetleri (huzurevi)' },
  { code: '8720', desc: 'Zihinsel engelli, ruh sagligi ve madde bagimliligi alaninda yatili bakim' },
  { code: '8730', desc: 'Yaslilar ve bedensel engelliler icin yatili bakimi' },
  { code: '8790', desc: 'Diger yatili bakim faaliyetleri' },
  { code: '8810', desc: 'Barinacak yer saglanmaksizin yaslilara ve engellilere bakim' },
  { code: '8891', desc: 'Gunduzlu cocuk bakim faaliyetleri (kres)' },
  { code: '8899', desc: 'Baska yerde siniflandirilmamis diger barinacak yer saglanmaksizin sosyal hizmetler' },

  // KULTUR, EGLENCE, SPOR (90-93)
  { code: '9001', desc: 'Gosteri sanatlari (tiyatro, muzik, dans)' },
  { code: '9002', desc: 'Gosteri sanatlarini destekleyici faaliyetler' },
  { code: '9003', desc: 'Sanatsal yaraticilik faaliyetleri' },
  { code: '9004', desc: 'Sanat tesislerinin isletilmesi' },
  { code: '9101', desc: 'Kutuphane ve arsiv faaliyetleri' },
  { code: '9102', desc: 'Muze ve tarihi yerlerin faaliyetleri' },
  { code: '9103', desc: 'Tarihi alanlar ve yapilar ile benzeri turistik yerlerin isletilmesi' },
  { code: '9104', desc: 'Botanik bahceleri, hayvanat bahceleri faaliyetleri' },
  { code: '9200', desc: 'Kumar ve musbet oyunlari faaliyetleri' },
  { code: '9311', desc: 'Spor tesis isletmeciligi' },
  { code: '9312', desc: 'Spor kulubu faaliyetleri' },
  { code: '9313', desc: 'Fitness salonu faaliyetleri' },
  { code: '9319', desc: 'Diger spor faaliyetleri' },
  { code: '9321', desc: 'Eglence parklari ve lunaparklarin faaliyetleri' },
  { code: '9329', desc: 'Baska yerde siniflandirilmamis diger eglence ve dinlence faaliyetleri' },

  // DIGER HIZMET FAALIYETLERI (94-96)
  { code: '9411', desc: 'Is ve isveren kurulusclarinin faaliyetleri' },
  { code: '9412', desc: 'Mesleki kurulusclarinin faaliyetleri' },
  { code: '9420', desc: 'Isccisendikaları faaliyetleri' },
  { code: '9491', desc: 'Dini kurulusclarinin faaliyetleri' },
  { code: '9492', desc: 'Siyasi kurulusclarinin faaliyetleri' },
  { code: '9499', desc: 'Baska yerde siniflandirilmamis diger uyelik org. faaliyetleri' },
  { code: '9511', desc: 'Bilgisayar ve cevre birimleri onarimi' },
  { code: '9512', desc: 'Iletisim ekipmanlari onarimi' },
  { code: '9521', desc: 'Tuketici elektronikmamul uerelerinin onarimi' },
  { code: '9522', desc: 'Ev aletleri ile ev ve bahce ekipmanlarinin onarimi' },
  { code: '9523', desc: 'Ayakkabi ve deri esya onarimi' },
  { code: '9524', desc: 'Mobilya ve ev dongenaatiminin onarimi' },
  { code: '9525', desc: 'Saat ve kuyumculuk urunleri onarimi' },
  { code: '9529', desc: 'Diger kisisel ve ev esyalarinin onarimi' },
  { code: '9601', desc: 'Tekstil ve kurk urunlerinin yikanmasi ve kuru temizlenmesi' },
  { code: '9602', desc: 'Kuafor ve diger guzellik salonlarinin faaliyetleri' },
  { code: '9603', desc: 'Cenaze ve ilgili faaliyetler' },
  { code: '9604', desc: 'Hamam, sauna, solaryum vb. fiziksel bakim faaliyetleri' },
  { code: '9609', desc: 'Baska yerde siniflandirilmamis diger hizmet faaliyetleri' },

  // HANE HALKI (97-98)
  { code: '9700', desc: 'Ev ici hizmetlerde istihdam eden hane halklari faaliyetleri' },
  { code: '9810', desc: 'Hane halklarinin kendi kullanimiicin ayrt edilmemis mal uretim faaliyetleri' },
  { code: '9820', desc: 'Hane halklarinin kendi kullanimiicin ayrt edilmemis hizmet uretimi' },

  // ULUSLARARASI ORGUTLER (99)
  { code: '9900', desc: 'Uluslararasi orgutlerin ve temsilciliklerinin faaliyetleri' },

  // ========== SIK KULLANILAN 6 HANELI NACE KODLARI ==========
  // TOPTAN TICARET (46.xx.xx)
  { code: '461101', desc: 'Tarimsal hammadde, canli hayvan komisyonculugu' },
  { code: '461102', desc: 'Tekstil hammaddeleri komisyonculugu' },
  { code: '461201', desc: 'Akaryakit, mineral, metal ve sanayi kimyasallari komisyonculugu' },
  { code: '461301', desc: 'Kereste ve insaat malzemeleri komisyonculugu' },
  { code: '461501', desc: 'Mobilya, ev esyasi ve hirdavat komisyonculugu' },
  { code: '461901', desc: 'Cesitli mallarin toptan ticaret komisyonculugu' },
  { code: '461902', desc: 'Gida maddeleri komisyonculugu' },
  { code: '462101', desc: 'Tahil, islenmis tohum ve hayvan yemi toptan ticareti' },
  { code: '462102', desc: 'Ham tutun toptan ticareti' },
  { code: '462201', desc: 'Cicek ve bitki toptan ticareti' },
  { code: '462301', desc: 'Canli hayvan toptan ticareti' },
  { code: '462401', desc: 'Ham deri, post ve derici malzemesi toptan ticareti' },
  { code: '463101', desc: 'Meyve ve sebze toptan ticareti' },
  { code: '463201', desc: 'Et ve et urunleri toptan ticareti' },
  { code: '463202', desc: 'Tavuk eti ve urunleri toptan ticareti' },
  { code: '463301', desc: 'Sut urunleri toptan ticareti' },
  { code: '463302', desc: 'Yumurta toptan ticareti' },
  { code: '463401', desc: 'Alkolllu ickecekler toptan ticareti' },
  { code: '463402', desc: 'Alkolsuz ickecekler toptan ticareti' },
  { code: '463601', desc: 'Seker, cikolata ve seker mamulleri toptan ticareti' },
  { code: '463701', desc: 'Kahve, cay, kakao ve baharat toptan ticareti' },
  { code: '463801', desc: 'Balik ve su urunleri toptan ticareti' },
  { code: '463901', desc: 'Gida maddelerinin belirli bir alanda uzmanlasmadan toptan ticareti' },
  { code: '464101', desc: 'Tekstil urunleri toptan ticareti' },
  { code: '464102', desc: 'Hazir giyim toptan ticareti' },
  { code: '464201', desc: 'Ayakkabi toptan ticareti' },
  { code: '464301', desc: 'Beyaz esya toptan ticareti' },
  { code: '464302', desc: 'Elektrikli ev aletleri toptan ticareti' },
  { code: '464501', desc: 'Parfumeri ve kozmetik urunleri toptan ticareti' },
  { code: '464601', desc: 'Tibbi ve eczacilik urunleri toptan ticareti' },
  { code: '464602', desc: 'Eczacilik urunleri toptan ticareti' },
  { code: '464701', desc: 'Mobilya toptan ticareti' },
  { code: '464702', desc: 'Hali ve kilim toptan ticareti' },
  { code: '464901', desc: 'Kirtasiye urunleri toptan ticareti' },
  { code: '464902', desc: 'Saat ve mucevherat toptan ticareti' },
  { code: '465101', desc: 'Bilgisayar, bilgisayar cevre birimleri toptan ticareti' },
  { code: '465201', desc: 'Elektronik ve telekomunikasyon parcalari toptan ticareti' },
  { code: '466101', desc: 'Tarim makinalari ve ekipmanlari toptan ticareti' },
  { code: '466201', desc: 'Takim tezgahlari toptan ticareti' },
  { code: '466301', desc: 'Maden ve insaat makinalari toptan ticareti' },
  { code: '466401', desc: 'Tekstil sanayi makinalari toptan ticareti' },
  { code: '466501', desc: 'Buro mobilyalari toptan ticareti' },
  { code: '466601', desc: 'Diger buro makinalari ve ekipmanlari toptan ticareti' },
  { code: '466901', desc: 'Diger makina ve ekipman toptan ticareti' },
  { code: '467101', desc: 'Kati, sivi ve gaz yakitlar toptan ticareti' },
  { code: '467102', desc: 'Akaryakit ve ilgili urunlerin toptan ticareti' },
  { code: '467201', desc: 'Metal ve metal cevheri toptan ticareti' },
  { code: '467301', desc: 'Agac, insaat malzemesi ve sihhi tesisat ekipmani toptan ticareti' },
  { code: '467302', desc: 'Boya, vernik, cam toptan ticareti' },
  { code: '467401', desc: 'Hirdavat, tesisat ve isitma ekipmani toptan ticareti' },
  { code: '467501', desc: 'Kimyasal urunler toptan ticareti' },
  { code: '467601', desc: 'Diger ara urunlerin toptan ticareti' },
  { code: '467701', desc: 'Hurda ve atik mallarin toptan ticareti' },
  { code: '469001', desc: 'Belirli bir mala tahsis edilmemis toptan ticaret' },
  // PERAKENDE TICARET (47.xx.xx)
  { code: '471101', desc: 'Belirli bir mala tahsis edilmemis magazalarda gida agirlikli perakende' },
  { code: '471102', desc: 'Market (33-400 m2)' },
  { code: '471103', desc: 'Supermarket (400-2500 m2)' },
  { code: '471104', desc: 'Hipermarket (2500 m2 ustu)' },
  { code: '471901', desc: 'Belirli bir mala tahsis edilmemis magazalarda diger perakende' },
  { code: '472101', desc: 'Meyve ve sebze perakende ticareti' },
  { code: '472201', desc: 'Et ve et urunleri perakende ticareti' },
  { code: '472301', desc: 'Balik ve su urunleri perakende ticareti' },
  { code: '472401', desc: 'Ekmek, pasta, unlu mamuller perakende ticareti' },
  { code: '472501', desc: 'Ickecek perakende ticareti' },
  { code: '472601', desc: 'Tutun urunleri perakende ticareti' },
  { code: '472901', desc: 'Diger gida urunleri perakende ticareti' },
  { code: '473001', desc: 'Akaryakit istasyonlarinda motorlu kara tasiti yakit perakende' },
  { code: '474101', desc: 'Bilgisayar, cevre birimleri ve yazilim perakende ticareti' },
  { code: '474201', desc: 'Telekomunikasyon ekipmani perakende ticareti' },
  { code: '475101', desc: 'Tekstil urunleri perakende ticareti' },
  { code: '477101', desc: 'Giyim esyasi perakende ticareti' },
  { code: '477201', desc: 'Ayakkabi ve deri esyalar perakende ticareti' },
  { code: '477301', desc: 'Eczaneler' },
  { code: '477401', desc: 'Tibbi ve ortopedik urunler perakende ticareti' },
  { code: '477501', desc: 'Kozmetik ve kisisel bakim urunleri perakende ticareti' },
  { code: '477601', desc: 'Cicek, bitki, tohum perakende ticareti' },
  { code: '477701', desc: 'Saat ve mucevherat perakende ticareti' },
  { code: '477801', desc: 'Optik urunlerin perakende ticareti' },
  { code: '477901', desc: 'Ikinci el esya perakende ticareti' },
  { code: '478101', desc: 'Semt pazarlarinda gida perakende ticareti' },
  { code: '478201', desc: 'Semt pazarlarinda giysi perakende ticareti' },
  { code: '479101', desc: 'Internet uzerinden perakende ticaret' },
  // INSAAT (41-43)
  { code: '411001', desc: 'Konut insaati icin proje gelistirme' },
  { code: '411002', desc: 'Konut disi insaat icin proje gelistirme' },
  { code: '412001', desc: 'Ikamet amacli binalarin insaati' },
  { code: '412002', desc: 'Ikamet amacli olmayan binalarin insaati' },
  { code: '421101', desc: 'Karayolu ve otoyol insaati' },
  { code: '422101', desc: 'Akiskan icin hizmet projeleri insaati' },
  { code: '422201', desc: 'Elektrik ve telekomunikasyon icin insaat' },
  { code: '429901', desc: 'Baska yerde siniflandirilmamis diger insaat projeleri' },
  { code: '431101', desc: 'Yikma isleri' },
  { code: '431201', desc: 'Arazi hazirlama isleri' },
  { code: '432101', desc: 'Elektrik tesisati isleri' },
  { code: '432201', desc: 'Sihhi tesisat, isitma ve klima tesisati isleri' },
  { code: '432901', desc: 'Diger insaat tesisati isleri' },
  { code: '433101', desc: 'Siva isleri' },
  { code: '433201', desc: 'Dograma montaj isleri' },
  { code: '433301', desc: 'Yer doseme ve duvar kaplama isleri' },
  { code: '433401', desc: 'Boya ve cam isleri' },
  { code: '433901', desc: 'Diger bina tamamlama ve bitirme isleri' },
  { code: '439101', desc: 'Cati isleri' },
  { code: '439901', desc: 'Baska yerde siniflandirilmamis ozel insaat faaliyetleri' },
  // YIYECEK ICECEK HIZMETLERI (56.xx.xx)
  { code: '561001', desc: 'Lokantalar ve restoranlar' },
  { code: '561002', desc: 'Kafeteryalar' },
  { code: '561003', desc: 'Fast food (hazir yemek) faaliyetleri' },
  { code: '561004', desc: 'Pideci, lahmacuncu, denerci vb.' },
  { code: '561005', desc: 'Kebapci, kofte salonu vb.' },
  { code: '562101', desc: 'Dugun, ziyafet organizasyonu' },
  { code: '562901', desc: 'Diger yemek hizmeti faaliyetleri' },
  { code: '563001', desc: 'Icecek sunum faaliyetleri (bar, kahvehane vb.)' },
  { code: '563002', desc: 'Cay ocagi, cay bahcesi isletmeciligi' },
  // NAKLIYAT (49.xx.xx)
  { code: '494101', desc: 'Karayolu yuk tasimaciligi' },
  { code: '494102', desc: 'Nakliyecilik' },
  { code: '493901', desc: 'Sehirler arasi yolcu tasimaciligi' },
  { code: '493201', desc: 'Taksi isletmeciligi' },
  // BILGI TEKNOLOJILERI (62.xx.xx)
  { code: '620101', desc: 'Bilgisayar programlama faaliyetleri' },
  { code: '620102', desc: 'Mobil uygulama gelistirme' },
  { code: '620201', desc: 'Bilgisayar danismanlik faaliyetleri' },
  { code: '620301', desc: 'Bilgisayar tesisleri yonetimi faaliyetleri' },
  { code: '620901', desc: 'Diger bilgi teknolojisi ve bilgisayar hizmet faaliyetleri' },
  { code: '631101', desc: 'Veri isleme, barindirma ve ilgili faaliyetler' },
  { code: '631201', desc: 'Web portallari' },
  // MUHASEBECILIK, DANISMANLIK, HUKUK (69-70)
  { code: '691001', desc: 'Hukuk faaliyetleri' },
  { code: '691002', desc: 'Avukatlik faaliyetleri' },
  { code: '692001', desc: 'Muhasebe, defter tutma ve denetim faaliyetleri' },
  { code: '692002', desc: 'Serbest muhasebeci mali musavirlik' },
  { code: '692003', desc: 'Yeminli mali musavirlik' },
  { code: '702101', desc: 'Halkla iliskiler ve iletisim faaliyetleri' },
  { code: '702201', desc: 'Isletme ve diger yonetim danismanligi faaliyetleri' },
  { code: '702202', desc: 'Vergi danismanligi' },
  // EMLAK (68.xx.xx)
  { code: '681001', desc: 'Kendi gayrimenkulunun alimi satimi' },
  { code: '682001', desc: 'Kendi gayrimenkulunun kiralanmasi ve isletilmesi' },
  { code: '683101', desc: 'Emlak acenteleri faaliyetleri' },
  { code: '683201', desc: 'Ucret veya sozlesme esasina dayali gayrimenkul yonetimi' },
  // SAGLIK (86.xx.xx)
  { code: '862101', desc: 'Genel tabiplik (muayenehane)' },
  { code: '862201', desc: 'Uzman tabiplik (muayenehane)' },
  { code: '862301', desc: 'Dis hekimligi (muayenehane)' },
  { code: '869001', desc: 'Diger insan sagligi hizmetleri' },
  // EGITIM (85.xx.xx)
  { code: '851001', desc: 'Okul oncesi egitim' },
  { code: '852001', desc: 'Ilkogretim' },
  { code: '853101', desc: 'Genel ortaogretim' },
  { code: '855101', desc: 'Spor ve eglence egitimi' },
  { code: '855201', desc: 'Kultur egitimi' },
  { code: '855901', desc: 'Diger egitim (surucu kursu, ozel ders vb.)' },
  { code: '855902', desc: 'Ozel ogretim kurslari' },
  // IMALAT DETAY (10-33)
  { code: '101101', desc: 'Sigir eti isleme ve muhafaza' },
  { code: '107101', desc: 'Ekmek, taze pastane urunleri imalati' },
  { code: '107102', desc: 'Pastane urunleri imalati' },
  { code: '107201', desc: 'Peksimet, biskuvi imalati' },
  { code: '108201', desc: 'Kakao, cikolata ve seker mamulleri imalati' },
  { code: '141301', desc: 'Diger dis giyim esyasi imalati' },
  { code: '141901', desc: 'Diger giyim esyasi ve aksesuarlari imalati' },
  { code: '251101', desc: 'Metal yapi ve yapi parcalari imalati' },
  { code: '251201', desc: 'Metal kapi ve pencere imalati' },
  { code: '252901', desc: 'Diger metal urunleri imalati' },
  { code: '310101', desc: 'Buro ve magaza mobilyalari imalati' },
  { code: '310201', desc: 'Mutfak mobilyalari imalati' },
  { code: '310901', desc: 'Diger mobilya imalati' },
]

// 4 haneli kodlari 6 haneye donustur (alt faaliyet kodu "01" eklenir)
const NACE_CODES_6 = NACE_CODES.map(n => ({
  ...n,
  code: n.code.length === 4 ? n.code + '01' : n.code
}))

export default NACE_CODES_6

// 6 haneli kodu XX.XX.XX formatinda gosterir
export function formatNaceCode(code) {
  if (!code) return ''
  const c = code.replace(/\./g, '').replace(/\s/g, '')
  if (c.length >= 6) return `${c.slice(0,2)}.${c.slice(2,4)}.${c.slice(4,6)}`
  if (c.length === 4) return `${c.slice(0,2)}.${c.slice(2,4)}`
  return code
}

// NACE kodu veya aciklama ile arama
export function searchNace(query) {
  if (!query || query.length < 2) return []
  const q = query.toLowerCase().replace(/\./g, '').replace(/\s/g, '')
  
  // Oncelikle tam veya parcali eslestirme
  let results = NACE_CODES_6.filter(n =>
    n.code.includes(q) || n.desc.toLowerCase().includes(q)
  )
  
  // Sonuc yoksa ve 5-6 haneli sayi girilmisse, ilk 4 haneye gore ara
  if (results.length === 0 && q.length >= 5 && /^\d+$/.test(q)) {
    const prefix = q.slice(0, 4)
    results = NACE_CODES_6.filter(n => n.code.startsWith(prefix))
  }
  
  // Hala sonuc yoksa ve 4+ haneli sayi girilmisse, ilk 2 haneye gore ara
  if (results.length === 0 && q.length >= 4 && /^\d+$/.test(q)) {
    const prefix = q.slice(0, 2)
    results = NACE_CODES_6.filter(n => n.code.startsWith(prefix))
  }
  
  return results.slice(0, 25)
}

// Kod ile faaliyet konusunu bul
export function getNaceDesc(code) {
  if (!code) return ''
  const c = code.replace(/\./g, '').replace(/\s/g, '')
  const found = NACE_CODES_6.find(n => n.code === c)
  return found ? found.desc : ''
}
